INSERT INTO USUARIO(ID, NOME) VALUES (100, 'MARIA');
INSERT INTO USUARIO(ID, NOME) VALUES (101, 'JOÃO');
INSERT INTO USUARIO(ID, NOME) VALUES (102, 'EDUARDA');
INSERT INTO USUARIO(ID, NOME) VALUES (103, 'MARCOS');