<<<<<<< HEAD
<<<<<<< HEAD
spring.application.name=techHorizon

# Configurando o URL de conecção com o MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/seubancodedados
=======
=======
>>>>>>> 275c4dacf315336d6689ef8fe7d3ad26be06422a
#spring.datasource.url=jdbc:mysql://localhost:3307/localtrackersql
#spring.datasource.username=devs
#spring.datasource.password=password123
#spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=mongodb+srv://user:123@techhorizon.dkxdv.mongodb.net/?retryWrites=true&w=majority&appName=TechHorizon
spring.data.mongodb.database=nosqllocaltracker
<<<<<<< HEAD
>>>>>>> 275c4dacf315336d6689ef8fe7d3ad26be06422a
=======
>>>>>>> 275c4dacf315336d6689ef8fe7d3ad26be06422a
