INSERT INTO DEVICE (ID, CODIGO, MAC_ADDRESS, USUARIO_ID) VALUES (100, 'CARD_01', 'ABC', 100);
INSERT INTO DEVICE (ID, CODIGO, MAC_ADDRESS, USUARIO_ID) VALUES (101, 'CARD_02', 'ABC', 101);
INSERT INTO DEVICE (ID, CODIGO, MAC_ADDRESS, USUARIO_ID) VALUES (102, 'CARD_03', 'ABC', 102);
INSERT INTO DEVICE (ID, CODIGO, MAC_ADDRESS, USUARIO_ID) VALUES (103, 'CARD_04', 'ABC', 103);